#!/usr/bin/perl

## Copyright (C) 2005 Walinsky
## This program is free software; you can redistribute it and/or modify it
## under the terms of the GNU General Public License as published by the 
## Free Software Foundation; either version 2 of the License, or (at your option)
## any later version.


# here goes

use XML::DOM;
$logFile="logfilenotify";
my $TimeStamp = time();
# we should check if it's a post message
if ($ENV{'REQUEST_METHOD'} eq 'POST') {
	read(STDIN, $my_data, $ENV{'CONTENT_LENGTH'});
	}
	
# set up HTML page
print "Content-Type: text/xml\n\n";


# uncheck following 3 lines if you want to record to your log File
open(LOGGER,">>$logFile") || `cat /dev/null > $logFile;chmod 666 $logFile`;
print LOGGER "indata was:\n".$my_data."\nI gave 'em \n".$answer."\n\n";
close(LOGGER);