#!/usr/bin/perl

## Copyright (C) 2005 Walinsky
## This program is free software; you can redistribute it and/or modify it
## under the terms of the GNU General Public License as published by the 
## Free Software Foundation; either version 2 of the License, or (at your option)
## any later version.

# here goes

use XML::DOM;
$logFile="logfile";
my $TimeStamp = time();
# we should check if it's a post message
if ($ENV{'REQUEST_METHOD'} eq 'POST') {
	read(STDIN, $my_data, $ENV{'CONTENT_LENGTH'});
	}
# instantiate parser
$xp = new XML::DOM::Parser();
# parse and create tree
$doc = $xp->parse($my_data);
# get root node
$root = $doc->getDocumentElement();
my $strings = $root->getElementsByTagName("methodName");
my $n = $strings->getLength;
for (my $i = 0; $i < $n; $i++)
 {
	my $string = $strings->item ($i)->getFirstChild()->getData;
	if ($string eq "subscription.list") {
		$answer = "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><methodResponse><params><param><value><struct><member><name>resultCode</name><value>Success</value></member><member><name>timestamp</name><value>$TimeStamp</value></member><member><name>resultBody</name><value><array><data></data></array></value></member></struct></value></param></params></methodResponse>";
		}
	elsif ($string eq "subscription.add") {
		$answer = "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><methodResponse><params><param><value><struct><member><name>resultCode</name><value>Success</value></member><member><name>timestamp</name><value>$TimeStamp</value></member><member><name>resultBody</name><value><array><data><value>Success</value></data></array></value></member></struct></value></param></params></methodResponse>";
		}
	elsif ($string eq "subscription.changedtags") {
		$answer = "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><methodResponse><params><param><value><struct><member><name>resultCode</name><value>Success</value></member><member><name>timestamp</name><value>$TimeStamp</value></member><member><name>resultBody</name><value><array><data></data></array></value></member></struct></value></param></params></methodResponse>";
		}
 }
	
# set up HTML page
print "Content-Type: text/xml\n\n";

print $answer;

# uncheck following 3 lines if you want to record to your log File
open(LOGGER,">>$logFile") || `cat /dev/null > $logFile;chmod 666 $logFile`;
print LOGGER "indata was:\n".$my_data."\nI gave 'em \n".$answer."\n\n";
close(LOGGER);