#!/usr/bin/perl -w

## Copyright (C) 2005 Walinsky
## This program is free software; you can redistribute it and/or modify it
## under the terms of the GNU General Public License as published by the 
## Free Software Foundation; either version 2 of the License, or (at your option)
## any later version.

use HTTPD::UserAdmin(); # used for accessing digest database can be found on http://search.cpan.org/
use CGI::Carp; # for neat logging to the error log

## for dumping all env variables uncomment the next 2 lines
# use Data::Dumper;
# carp Dumper(\%ENV);

my $dbFile = "/etc/httpd/auth/webdav/iDiskUsers"; # change this to the location of your digest database

my $username = "";
my $password = "";
my $service = "";
my $systemVersion = "";
my $dotmacversion = "";

#  my $documentroot = $tree->lookup('DocumentRoot');
if ($ENV{'REQUEST_METHOD'} eq 'POST') {
	read(STDIN, $my_data, $ENV{'CONTENT_LENGTH'});
	}
carp $my_data;
my(@name_value_array) = split(/;/, $my_data);
foreach $name_value_pair (@name_value_array) {
	chomp ($name_value_pair);
	my($name, $value) = split(/ = /, $name_value_pair);
	if ($name =~ m/username/){ $username = $value; }
	elsif ($name =~ m/password/){ $password = $value; }
	elsif ($name =~ m/service/){ $service = $value; }
	elsif ($name =~ m/systemVersion/){ $systemVersion = $value; }
	elsif ($name =~ m/version/){ $dotmacversion = $value; }
	}




@htfile = (	DBType => 'Text',
			DB     => $dbFile,
			Server => 'apache',
			Encrypt => 'MD5');
$user = new HTTPD::UserAdmin @htfile;
# grab realm:hashedpassword from digest database
$info = $user->password($username);
my($realm, $checksum) = split(":", $info);
# generate realm:hashedpassword from supplied password
my $digestpassword =$user->encrypt("$username:$realm:$password");
if ($info eq $digestpassword) {
	$answer = "{
    messageHTML = \"<html><head></head><body><b>Thanks $username for being a member</b><br>Your account will expire when our server dies, but you'll be probably dead by then.<br>Need additional email or iDisk space? Feel free to buy me some harddisks.<br><br>\n<div style='position:absolute; left:0px; bottom:0px;'><IMG src='http://www.walinsky.com/dotwalinskysmall.png' alt='dotwalinsky' width='50' height='61' /></div><div style='position:absolute; right:0px; bottom:0px;'><input type=submit style='font-size:18px' value='Info&nbsp;' onclick='document.location.href=\\\"http://www.walinsky.com/dotmac/\\\"'></div></body></html>\"; 
    service = dotMacPreferencesPaneMessage; 
    servicesAvailable = (iDisk, iSync, Backup, iChatEncryption, Email, WebHosting); 
    statusCode = success; 
    version = 1; 
}";
	warn "user: $username got a beautiful welcome message on the dotMacPreferencesPane";
	}
else	{
	$answer = "{
    forgottenPasswordURL = \"http://www.walinsky.com/dotmac/\"; 
    statusCode = authorizationFailed; 
}";
	warn "$username didn't have a valid login";
}

# set up HTML page
print "Content-Type: text/plain\n\n";
print $answer;
