#!/usr/bin/perl -w

## Copyright (C) 2005 Walinsky
## This program is free software; you can redistribute it and/or modify it
## under the terms of the GNU General Public License as published by the 
## Free Software Foundation; either version 2 of the License, or (at your option)
## any later version.

use HTTPD::UserAdmin(); # used for accessing digest database can be found on http://search.cpan.org/
my $dbFile = "/etc/httpd/auth/webdav/iDiskUsers"; # change this to the location of your digest database

# Grab the username and password from the input data.
while(<STDIN>){
 if ( /username\s+=\s+(.*?)\;/ ){
   $username = $1;;
 }

 if ( /password\s+=\s+(.*?)\;/ ){
   $password = $1;;
 }
}

@htfile = (	DBType => 'Text',
			DB     => $dbFile,
			Server => 'apache',
			Encrypt => 'MD5');
$user = new HTTPD::UserAdmin @htfile;
# grab realm:hashedpassword from digest database
$info = $user->password($username);
my($realm, $checksum) = split(":", $info);
# generate realm:hashedpassword from supplied password
my $digestpassword =$user->encrypt("$username:$realm:$password");
if ($info eq $digestpassword) {
	$answer = "{
    messageHTML = \"<html><head></head><body><b>Thanks $username for being a member</b><br><br>Your account will expire when our server dies, but you'll be probably dead by then.<br>Need additional email or iDisk space? Feel free to buy me some harddisks.<br><br>\n<div style='position:absolute; right:0px; bottom:0px;'><input type=submit style='font-size:18px' value='Info&nbsp;' onclick='document.location.href=\\\"http://www.walinsky.com/dotmac/\\\"'></div></body></html>\"; 
    service = dotMacPreferencesPaneMessage; 
    servicesAvailable = (iDisk, iSync, Backup, iChatEncryption, Email, WebHosting); 
    statusCode = success; 
    version = 1; 
}";
	}
else	{
	$answer = "{
    forgottenPasswordURL = \"http://www.walinsky.com/dotmac/\"; 
    statusCode = authorizationFailed; 
}";
}

# set up HTML page
print "Content-Type: text/plain\n\n";
print $answer;
